### PR TITLE
fix: simulated HTTP errors now delayed as expected

### LINKED ISSUE #180: Class 'HttpClientBackendService' incorrectly implements interface 'HttpBackend'.
When compiling angular.io examples after update to rxjs v6 I'm getting the following error:
```
node_modules/angular-in-memory-web-api/http-client-backend.service.d.ts(32,22): error TS2420: Class 'HttpClientBackendService' incorrectly implements interface 'HttpBackend'.
  Types of property 'handle' are incompatible.
    Type '(req: HttpRequest<any>) => Observable<HttpResponse<any>>' is not assignable to type '(req: HttpRequest<any>) => Observable<HttpEvent<any>>'.
      Type 'Observable<HttpResponse<any>>' is not assignable to type 'Observable<HttpEvent<any>>'.
        Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.
```

I haven't investigated why this error is surfaced only now, but it does seem that the interface is incorrectly implemented. See:

https://github.com/angular/in-memory-web-api/blob/748891871fdb61d071f9dbf57fa8174924cebfb7/src/in-mem/http-client-backend.service.ts#L64

Which returns an `Observable<HttpResponse<any>>` and not it's super class `Observable<HttpEvent<any>>`.

Found in version: 0.5.3

Workaround: disable typecheck of 3rd party code by setting `"skipLibCheck": true` in tsconfig.json.

### PR DESCRIPTION
**Pull request by wardbell**
Fixes bug in which a simulated HTTP error did NOT honor the prescribed latency delay.
New `makeResponseDelay()` function cures that.
Added tests for this.

Library no longer uses RxJS `delay()` which may make userland tests easier because Angular TestBed "hates" RxJS `delay()` (it uses `interval()`).

Also closes #180.

When this PR is merged, can publish the new version to NPM as **release 0.5.4**.

### CODE REVIEW

File: src/in-mem/delay-response.ts [hunk 1]
```diff
@@ -0,0 +1,30 @@
+import { Observable } from 'rxjs/Observable';
+
+/** adds specified delay (in ms) to both next and error channels of the response observable */
```
Comment (IgorMinar) [inline src/in-mem/delay-response.ts]: please add docs you wrote for changelog also here so that nobody reading the code is wondering why we have a custom delay operator.

File: CHANGELOG.md [hunk 2]
```diff
@@ -8,7 +8,21 @@ because this is a development tool, not a production product.
 We do try to tell you about such changes in this `CHANGELOG.md`
 and we fix bugs as fast as we can.
 
-<a id="0.5.2"></a>
+
+<a id="0.5.4"></a>
+## 0.5.4 (2018-03-09)
+
+Simulated HTTP error responses were not delaying the prescribed time when using RxJS `delay()`
```
Comment (wardbell) [inline CHANGELOG.md]: Describes the change to the implementation of simulated delay

File: src/in-mem/backend.service.ts [hunk 3]
```diff
@@ -160,7 +160,7 @@ export abstract class BackendService {
    */
   protected addDelay(response: Observable<any>): Observable<any> {
     const d = this.config.delay;
-    return d === 0 ? response : delay.call(response, d || 500);
```
Comment (wardbell) [inline src/in-mem/backend.service.ts]: Replaces RxJS `delay()` (incorrect for errors) with new `delayRespons()` function.

File: src/in-mem/delay-response.ts (hunk 1 above)
Comment (wardbell) [reply src/in-mem/delay-response.ts]: Added reference to the CHANGELOG

**Comment by wardbell** [comment]
Piggy backed fix to issue #180
